Add figma link in issue template
layer5io/slack pull request #16
Opened 2023-07-17 03:58 UTC by sahilyeole

**Description**
Added figma link in issue template as per the instructions
This PR fixes #15 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

2023-07-18 15:09 UTC, thisiskaransgit requested changes
@sahilyeole, we needed the layer5 design file here in place of Meshery UI, please update the PR

2023-07-18 15:09 UTC, thisiskaransgit commented on .github/ISSUE_TEMPLATE/documentation.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```suggestion
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

2023-07-18 15:32 UTC, sahilyeole commented on .github/ISSUE_TEMPLATE/documentation.md
> +- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
Done 👍

2023-07-18 15:34 UTC, sahilyeole commented
Hey @thisiskaransgit, I've made the changes that you have suggested can you please review it?

2023-07-19 04:34 UTC, leecalcote approved these changes
Thanks!

2023-07-19 04:49 UTC, merged